name: Trigger auto deployment for container-app-c4636ub4ysksq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'docker/api/**'
    - '.github/workflows/container-app-c4636ub4ysksq-AutoDeployTrigger-5a3b38ae-86c0-4988-91f1-941912eeb14c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPC4636UB4YSKSQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPC4636UB4YSKSQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPC4636UB4YSKSQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/docker/api 
          registryUrl: containerregistryc4636ub4ysksq.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPC4636UB4YSKSQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPC4636UB4YSKSQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-c4636ub4ysksq
          resourceGroup: fastapiboilerplatebf7d
          imageToBuild: containerregistryc4636ub4ysksq.azurecr.io/container-app-c4636ub4ysksq:${{ github.sha }}
          dockerfilePath: Dockerfile


